#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-XML-NamespaceSupport
Version  : 1.12.9
Release  : 8
URL      : https://www.cpan.org/authors/id/P/PE/PERIGRIN/XML-NamespaceSupport-1.12_9.tar.gz
Source0  : https://www.cpan.org/authors/id/P/PE/PERIGRIN/XML-NamespaceSupport-1.12_9.tar.gz
Summary  : 'A simple generic namespace processor'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-1.0
Requires: perl-XML-NamespaceSupport-doc

%description
# XML::NamespaceSupport
This module offers a simple way to process namespaced XML names (unames)
from within any application that may need them. It also helps maintain a
prefix to namespace URI map, and provides a number of basic checks.

%package doc
Summary: doc components for the perl-XML-NamespaceSupport package.
Group: Documentation

%description doc
doc components for the perl-XML-NamespaceSupport package.


%prep
%setup -q -n XML-NamespaceSupport-1.12_9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make V=1  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.24.0/XML/NamespaceSupport.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
