#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-XML-NamespaceSupport
Version  : 1.12
Release  : 34
URL      : https://cpan.metacpan.org/authors/id/P/PE/PERIGRIN/XML-NamespaceSupport-1.12.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PE/PERIGRIN/XML-NamespaceSupport-1.12.tar.gz
Summary  : 'A simple generic namespace processor'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-XML-NamespaceSupport-license = %{version}-%{release}
Requires: perl-XML-NamespaceSupport-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
XML::NamespaceSupport
This module offers a simple way to process namespaced XML names
(unames) from within any application that may need them. It
also helps maintain a prefix to namespace URI map, and provides
a number of basic checks.

%package dev
Summary: dev components for the perl-XML-NamespaceSupport package.
Group: Development
Provides: perl-XML-NamespaceSupport-devel = %{version}-%{release}
Requires: perl-XML-NamespaceSupport = %{version}-%{release}

%description dev
dev components for the perl-XML-NamespaceSupport package.


%package license
Summary: license components for the perl-XML-NamespaceSupport package.
Group: Default

%description license
license components for the perl-XML-NamespaceSupport package.


%package perl
Summary: perl components for the perl-XML-NamespaceSupport package.
Group: Default
Requires: perl-XML-NamespaceSupport = %{version}-%{release}

%description perl
perl components for the perl-XML-NamespaceSupport package.


%prep
%setup -q -n XML-NamespaceSupport-1.12
cd %{_builddir}/XML-NamespaceSupport-1.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-XML-NamespaceSupport
cp %{_builddir}/XML-NamespaceSupport-1.12/LICENSE %{buildroot}/usr/share/package-licenses/perl-XML-NamespaceSupport/c45574961a40fa36f666c6de7712e51fd54f9fef
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/XML::NamespaceSupport.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-XML-NamespaceSupport/c45574961a40fa36f666c6de7712e51fd54f9fef

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.34.0/XML/NamespaceSupport.pm
