#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-XML-NamespaceSupport
Version  : 1.12
Release  : 15
URL      : https://cpan.metacpan.org/authors/id/P/PE/PERIGRIN/XML-NamespaceSupport-1.12.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PE/PERIGRIN/XML-NamespaceSupport-1.12.tar.gz
Summary  : 'A simple generic namespace processor'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-XML-NamespaceSupport-license
Requires: perl-XML-NamespaceSupport-man

%description
XML::NamespaceSupport
This module offers a simple way to process namespaced XML names
(unames) from within any application that may need them. It
also helps maintain a prefix to namespace URI map, and provides
a number of basic checks.

%package license
Summary: license components for the perl-XML-NamespaceSupport package.
Group: Default

%description license
license components for the perl-XML-NamespaceSupport package.


%package man
Summary: man components for the perl-XML-NamespaceSupport package.
Group: Default

%description man
man components for the perl-XML-NamespaceSupport package.


%prep
%setup -q -n XML-NamespaceSupport-1.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-XML-NamespaceSupport
cp LICENSE %{buildroot}/usr/share/doc/perl-XML-NamespaceSupport/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/XML/NamespaceSupport.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-XML-NamespaceSupport/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/XML::NamespaceSupport.3
